package model;

public enum AFFIDAVIT_ENUM {
    CAUSE_NUMBER,
    COURT_INFO,
    PLAINTIFF,
    DEFENDANT,
    FACILITIES,
    DATE_OF_INJURY,
    EXPERT_OPINION,
    TREATMENTS,
    GENERATE_DATE
}
